// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6oAalLvedovwuaa9oedilH-541U9qf5s',
    appId: '1:624794657391:web:e1db50b76b1564a5a8a39a',
    messagingSenderId: '624794657391',
    projectId: 'cmsc23-pnsemillano',
    authDomain: 'cmsc23-pnsemillano.firebaseapp.com',
    storageBucket: 'cmsc23-pnsemillano.appspot.com',
    measurementId: 'G-BCJ61KH3C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRs1VEsVocmT2uOK4yOa0L-6lEDAjwW9g',
    appId: '1:624794657391:android:c6a931a6a139cb26a8a39a',
    messagingSenderId: '624794657391',
    projectId: 'cmsc23-pnsemillano',
    storageBucket: 'cmsc23-pnsemillano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApWtMSCeUBf-pD5AA6cASEZfT19X58Qpo',
    appId: '1:624794657391:ios:d33d0e5c58535ca0a8a39a',
    messagingSenderId: '624794657391',
    projectId: 'cmsc23-pnsemillano',
    storageBucket: 'cmsc23-pnsemillano.appspot.com',
    iosClientId:
        '624794657391-lesfoh08n5d4ug3j1blink9doff8docs.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApWtMSCeUBf-pD5AA6cASEZfT19X58Qpo',
    appId: '1:624794657391:ios:d33d0e5c58535ca0a8a39a',
    messagingSenderId: '624794657391',
    projectId: 'cmsc23-pnsemillano',
    storageBucket: 'cmsc23-pnsemillano.appspot.com',
    iosClientId:
        '624794657391-lesfoh08n5d4ug3j1blink9doff8docs.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
